### PR TITLE
Add missing libs and other stuff

### PR DESCRIPTION
**Pull request by cristiniita**
Base proprietary-files.txt was missing a lot of stuff from common-vendor so i just added remaining.

### CODE REVIEW

**Comment by argraur** [comment]
Uhh no one will check your pull request
Use Gerrit instead.

**Comment by 0xXA** [comment]
The concept is pretty straight forward we take non-opensourced vendor specific libs like display, audio hals, etc

**Comment by ItzLevvie** [comment]
Hey there, @Shenhua99!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
